on:
  release:
    types: [published]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        cabal: ["3.4"]
        ghc: ["8.10.7", "9.0.1"]
    runs-on: ${{ matrix.platform }}
    
    name: Compile quark on Linux
    steps:
      - uses: actions/checkout@master
      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      
      - name: Compile and ZIP Quark on Unix
        if: matrix.platform != 'windows-latest'
        run: |
          cabal build
          find dist-newstyle -type f -name 'quark' -exec mv '{}' quark \;
          zip -r 'quark-${{ matrix.platform }}.zip' quark library README.md
          
      - name: Compile and ZIP Quark on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          cabal build
          Get-ChildItem -Filter quark.exe -Recurse $pwd | Foreach {mv $_.fullname quark.exe}
          Compress-Archive -CompressionLevel Optimal -Force -Path quark.exe, library, README.md -DestinationPath 'quark-${{ matrix.platform }}.zip' 
        
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: './quark-${{ matrix.platform }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
